name: CI/CD Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '14'

    - name: Install dependencies
      run: npm install

    - name: Run tests
      run: npm test

    - name: Deploy to AWS
      if: github.ref == 'refs/heads/main'
      run: |
        ssh -i "rajat.pem" ec2-user@ 54.221.142.106<< 'EOF'
        cd /path/to/your/app
        git pull origin main
        npm install
        npm restart all
        EOF
